DROP TABLE IF EXISTS municipality;
DROP TABLE IF EXISTS counties;

CREATE TABLE counties(
  name VARCHAR(255) PRIMARY KEY NOT NULL
);

CREATE TABLE municipality(
  name VARCHAR(255) NOT NULL,
  county varchar(255) NOT NULL REFERENCES counties(name),
  PRIMARY KEY (name,county)
);


INSERT INTO counties VALUES ('Trøndelag');
INSERT INTO counties VALUES ('Oppland');
INSERT INTO counties VALUES ('Oslo');
INSERT INTO counties VALUES ('Nordland');
INSERT INTO counties VALUES ('Telemark');
INSERT INTO counties VALUES ('Hedmark');
INSERT INTO counties VALUES ('Akershus');
INSERT INTO counties VALUES ('Aust-Agder');
INSERT INTO counties VALUES ('Vest-Agder');
INSERT INTO counties VALUES ('Sogn og Fjordane');
INSERT INTO counties VALUES ('Møre og Romsdal');
INSERT INTO counties VALUES ('Finnmark');
INSERT INTO counties VALUES ('Troms');
INSERT INTO counties VALUES ('Hordaland');
INSERT INTO counties VALUES ('Buskerud');
INSERT INTO counties VALUES ('Rogaland');
INSERT INTO counties VALUES ('Østfold');


INSERT INTO municipality(name, county) VALUES('Halden', 'Østfold');
INSERT INTO municipality(name, county) VALUES('Moss', 'Østfold');
INSERT INTO municipality(name, county) VALUES('Sarpsborg', 'Østfold');
INSERT INTO municipality(name, county) VALUES('Fredrikstad', 'Østfold');
INSERT INTO municipality(name, county) VALUES('Hvaler', 'Østfold');
INSERT INTO municipality(name, county) VALUES('Aremark', 'Østfold');
INSERT INTO municipality(name, county) VALUES('Marker', 'Østfold');
INSERT INTO municipality(name, county) VALUES('Rømskog', 'Østfold');
INSERT INTO municipality(name, county) VALUES('Trøgstad', 'Østfold');
INSERT INTO municipality(name, county) VALUES('Spydeberg', 'Østfold');
INSERT INTO municipality(name, county) VALUES('Askim', 'Østfold');
INSERT INTO municipality(name, county) VALUES('Eidsberg', 'Østfold');
INSERT INTO municipality(name, county) VALUES('Skiptvet', 'Østfold');
INSERT INTO municipality(name, county) VALUES('Rakkestad', 'Østfold');
INSERT INTO municipality(name, county) VALUES('Råde', 'Østfold');
INSERT INTO municipality(name, county) VALUES('Rygge', 'Østfold');
INSERT INTO municipality(name, county) VALUES('Våler', 'Østfold');
INSERT INTO municipality(name, county) VALUES('Hobøl', 'Østfold');
INSERT INTO municipality(name, county) VALUES('Vestby', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Ski', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Ås', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Frogn', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Nesodden', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Oppegård', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Bærum', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Asker', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Aurskog-Høland', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Sørum', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Fet', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Rælingen', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Enebakk', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Lørenskog', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Skedsmo', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Nittedal', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Gjerdrum', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Ullensaker', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Nes', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Eidsvoll', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Nannestad', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Hurdal', 'Akershus');
INSERT INTO municipality(name, county) VALUES('Oslo', 'Oslo');
INSERT INTO municipality(name, county) VALUES('Kongsvinger', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Hamar', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Ringsaker', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Løten', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Stange', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Nord-Odal', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Sør-Odal', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Eidskog', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Grue', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Åsnes', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Våler', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Elverum', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Trysil', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Åmot', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Stor-Elvdal', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Rendalen', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Engerdal', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Tolga', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Tynset', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Alvdal', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Folldal', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Os', 'Hedmark');
INSERT INTO municipality(name, county) VALUES('Lillehammer', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Gjøvik', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Dovre', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Lesja', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Skjåk', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Lom', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Vågå', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Nord-Fron', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Sel', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Sør-Fron', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Ringebu', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Øyer', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Gausdal', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Østre Toten', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Vestre Toten', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Jevnaker', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Lunner', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Gran', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Søndre Land', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Nordre Land', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Sør-Aurdal', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Etnedal', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Nord-Aurdal', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Vestre Slidre', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Øystre Slidre', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Vang', 'Oppland');
INSERT INTO municipality(name, county) VALUES('Drammen', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Kongsberg', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Ringerike', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Hole', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Flå', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Nes', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Gol', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Hemsedal', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Ål', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Hol', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Sigdal', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Krødsherad', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Modum', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Øvre Eiker', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Nedre Eiker', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Lier', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Røyken', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Hurum', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Flesberg', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Rollag', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Nore og Uvdal', 'Buskerud');
INSERT INTO municipality(name, county) VALUES('Horten', 'Vestfold');
INSERT INTO municipality(name, county) VALUES('Tønsberg', 'Vestfold');
INSERT INTO municipality(name, county) VALUES('Sandefjord', 'Vestfold');
INSERT INTO municipality(name, county) VALUES('Svelvik', 'Vestfold');
INSERT INTO municipality(name, county) VALUES('Larvik', 'Vestfold');
INSERT INTO municipality(name, county) VALUES('Sande', 'Vestfold');
INSERT INTO municipality(name, county) VALUES('Holmestrand', 'Vestfold');
INSERT INTO municipality(name, county) VALUES('Re', 'Vestfold');
INSERT INTO municipality(name, county) VALUES('Færder', 'Vestfold');
INSERT INTO municipality(name, county) VALUES('Porsgrunn', 'Telemark');
INSERT INTO municipality(name, county) VALUES('Skien', 'Telemark');
INSERT INTO municipality(name, county) VALUES('Notodden', 'Telemark');
INSERT INTO municipality(name, county) VALUES('Siljan', 'Telemark');
INSERT INTO municipality(name, county) VALUES('Bamble', 'Telemark');
INSERT INTO municipality(name, county) VALUES('Kragerø', 'Telemark');
INSERT INTO municipality(name, county) VALUES('Drangedal', 'Telemark');
INSERT INTO municipality(name, county) VALUES('Nome', 'Telemark');
INSERT INTO municipality(name, county) VALUES('Bø', 'Telemark');
INSERT INTO municipality(name, county) VALUES('Sauherad', 'Telemark');
INSERT INTO municipality(name, county) VALUES('Tinn', 'Telemark');
INSERT INTO municipality(name, county) VALUES('Hjartdal', 'Telemark');
INSERT INTO municipality(name, county) VALUES('Seljord', 'Telemark');
INSERT INTO municipality(name, county) VALUES('Kviteseid', 'Telemark');
INSERT INTO municipality(name, county) VALUES('Nissedal', 'Telemark');
INSERT INTO municipality(name, county) VALUES('Fyresdal', 'Telemark');
INSERT INTO municipality(name, county) VALUES('Tokke', 'Telemark');
INSERT INTO municipality(name, county) VALUES('Vinje', 'Telemark');
INSERT INTO municipality(name, county) VALUES('Risør', 'Aust-Agder');
INSERT INTO municipality(name, county) VALUES('Grimstad', 'Aust-Agder');
INSERT INTO municipality(name, county) VALUES('Arendal', 'Aust-Agder');
INSERT INTO municipality(name, county) VALUES('Gjerstad', 'Aust-Agder');
INSERT INTO municipality(name, county) VALUES('Vegårshei', 'Aust-Agder');
INSERT INTO municipality(name, county) VALUES('Tvedestrand', 'Aust-Agder');
INSERT INTO municipality(name, county) VALUES('Froland', 'Aust-Agder');
INSERT INTO municipality(name, county) VALUES('Lillesand', 'Aust-Agder');
INSERT INTO municipality(name, county) VALUES('Birkenes', 'Aust-Agder');
INSERT INTO municipality(name, county) VALUES('Åmli', 'Aust-Agder');
INSERT INTO municipality(name, county) VALUES('Iveland', 'Aust-Agder');
INSERT INTO municipality(name, county) VALUES('Evje og Hornnes', 'Aust-Agder');
INSERT INTO municipality(name, county) VALUES('Bygland', 'Aust-Agder');
INSERT INTO municipality(name, county) VALUES('Valle', 'Aust-Agder');
INSERT INTO municipality(name, county) VALUES('Bykle', 'Aust-Agder');
INSERT INTO municipality(name, county) VALUES('Kristiansand', 'Vest-Agder');
INSERT INTO municipality(name, county) VALUES('Mandal', 'Vest-Agder');
INSERT INTO municipality(name, county) VALUES('Farsund', 'Vest-Agder');
INSERT INTO municipality(name, county) VALUES('Flekkefjord', 'Vest-Agder');
INSERT INTO municipality(name, county) VALUES('Vennesla', 'Vest-Agder');
INSERT INTO municipality(name, county) VALUES('Songdalen', 'Vest-Agder');
INSERT INTO municipality(name, county) VALUES('Søgne', 'Vest-Agder');
INSERT INTO municipality(name, county) VALUES('Marnardal', 'Vest-Agder');
INSERT INTO municipality(name, county) VALUES('Åseral', 'Vest-Agder');
INSERT INTO municipality(name, county) VALUES('Audnedal', 'Vest-Agder');
INSERT INTO municipality(name, county) VALUES('Lindesnes', 'Vest-Agder');
INSERT INTO municipality(name, county) VALUES('Lyngdal', 'Vest-Agder');
INSERT INTO municipality(name, county) VALUES('Hægebostad', 'Vest-Agder');
INSERT INTO municipality(name, county) VALUES('Kvinesdal', 'Vest-Agder');
INSERT INTO municipality(name, county) VALUES('Sirdal', 'Vest-Agder');
INSERT INTO municipality(name, county) VALUES('Eigersund', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Sandnes', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Stavanger', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Haugesund', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Sokndal', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Lund', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Bjerkreim', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Hå', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Klepp', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Time', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Gjesdal', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Sola', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Randaberg', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Forsand', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Strand', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Hjelmeland', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Suldal', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Sauda', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Finnøy', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Rennesøy', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Kvitsøy', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Bokn', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Tysvær', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Karmøy', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Utsira', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Vindafjord', 'Rogaland');
INSERT INTO municipality(name, county) VALUES('Bergen', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Etne', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Sveio', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Bømlo', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Stord', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Fitjar', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Tysnes', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Kvinnherad', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Jondal', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Odda', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Ullensvang', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Eidfjord', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Ulvik', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Granvin', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Voss', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Kvam', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Fusa', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Samnanger', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Os', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Austevoll', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Sund', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Fjell', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Askøy', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Vaksdal', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Modalen', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Osterøy', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Meland', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Øygarden', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Radøy', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Lindås', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Austrheim', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Fedje', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Masfjorden', 'Hordaland');
INSERT INTO municipality(name, county) VALUES('Flora', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Gulen', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Solund', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Hyllestad', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Høyanger', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Vik', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Balestrand', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Leikanger', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Sogndal', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Aurland', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Lærdal', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Årdal', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Luster', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Askvoll', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Fjaler', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Gaular', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Jølster', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Førde', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Naustdal', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Bremanger', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Vågsøy', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Selje', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Eid', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Hornindal', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Gloppen', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Stryn', 'Sogn og Fjordane');
INSERT INTO municipality(name, county) VALUES('Molde', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Ålesund', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Kristiansund', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Vanylven', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Sande', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Herøy', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Ulstein', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Hareid', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Volda', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Ørsta', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Ørskog', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Norddal', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Stranda', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Stordal', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Sykkylven', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Skodje', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Sula', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Giske', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Haram', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Vestnes', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Rauma', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Nesset', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Midsund', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Sandøy', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Aukra', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Fræna', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Eide', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Averøy', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Gjemnes', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Tingvoll', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Sunndal', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Surnadal', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Halsa', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Smøla', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Aure', 'Møre og Romsdal');
INSERT INTO municipality(name, county) VALUES('Bodø', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Narvik', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Bindal', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Sømna', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Brønnøy', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Vega', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Vevelstad', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Herøy', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Alstahaug', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Leirfjord', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Vefsn', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Grane', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Hattfjelldal', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Dønna', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Nesna', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Hemnes', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Rana', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Lurøy', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Træna', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Rødøy', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Meløy', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Gildeskål', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Beiarn', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Saltdal', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Fauske', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Sørfold', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Steigen', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Hamarøy', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Tysfjord', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Lødingen', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Tjeldsund', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Evenes', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Ballangen', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Røst', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Værøy', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Flakstad', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Vestvågøy', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Vågan', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Hadsel', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Bø', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Øksnes', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Sortland', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Andøy', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Moskenes', 'Nordland');
INSERT INTO municipality(name, county) VALUES('Harstad[13]', 'Troms');
INSERT INTO municipality(name, county) VALUES('Tromsø', 'Troms');
INSERT INTO municipality(name, county) VALUES('Kvæfjord', 'Troms');
INSERT INTO municipality(name, county) VALUES('Skånland', 'Troms');
INSERT INTO municipality(name, county) VALUES('Ibestad', 'Troms');
INSERT INTO municipality(name, county) VALUES('Gratangen', 'Troms');
INSERT INTO municipality(name, county) VALUES('Lavangen', 'Troms');
INSERT INTO municipality(name, county) VALUES('Bardu', 'Troms');
INSERT INTO municipality(name, county) VALUES('Salangen', 'Troms');
INSERT INTO municipality(name, county) VALUES('Målselv', 'Troms');
INSERT INTO municipality(name, county) VALUES('Sørreisa', 'Troms');
INSERT INTO municipality(name, county) VALUES('Dyrøy', 'Troms');
INSERT INTO municipality(name, county) VALUES('Tranøy', 'Troms');
INSERT INTO municipality(name, county) VALUES('Torsken', 'Troms');
INSERT INTO municipality(name, county) VALUES('Berg', 'Troms');
INSERT INTO municipality(name, county) VALUES('Lenvik', 'Troms');
INSERT INTO municipality(name, county) VALUES('Balsfjord', 'Troms');
INSERT INTO municipality(name, county) VALUES('Karlsøy', 'Troms');
INSERT INTO municipality(name, county) VALUES('Lyngen', 'Troms');
INSERT INTO municipality(name, county) VALUES('Storfjord', 'Troms');
INSERT INTO municipality(name, county) VALUES('Kåfjord', 'Troms');
INSERT INTO municipality(name, county) VALUES('Skjervøy', 'Troms');
INSERT INTO municipality(name, county) VALUES('Nordreisa', 'Troms');
INSERT INTO municipality(name, county) VALUES('Kvænangen', 'Troms');
INSERT INTO municipality(name, county) VALUES('Vardø', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Vadsø', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Hammerfest', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Kautokeino', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Alta', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Loppa', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Hasvik', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Kvalsund', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Måsøy', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Nordkapp', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Porsanger', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Karasjok', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Lebesby', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Gamvik', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Berlevåg', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Tana', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Nesseby', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Båtsfjord', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Sør-Varanger', 'Finnmark');
INSERT INTO municipality(name, county) VALUES('Trondheim', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Steinkjer', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Namsos', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Hemne', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Snillfjord', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Hitra', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Frøya', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Ørland', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Agdenes', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Bjugn', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Åfjord', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Roan', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Osen', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Oppdal', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Rennebu', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Meldal', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Orkdal', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Røros', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Holtålen', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Midtre Gauldal', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Melhus', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Skaun', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Klæbu', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Malvik', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Selbu', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Tydal', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Meråker', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Stjørdal', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Frosta', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Levanger', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Verdal', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Verran', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Namdalseid', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Snåsa', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Lierne', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Røyrvik', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Namsskogan', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Grong', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Høylandet', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Overhalla', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Fosnes', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Flatanger', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Vikna', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Nærøy', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Leka', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Inderøy', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Indre Fosen', 'Trøndelag');
INSERT INTO municipality(name, county) VALUES('Rindal', 'Trøndelag');
